POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "NLW Unite Rocketseat",
    "details": "Um evento topzera das galáxias, para os amantes de tecnologia! 🚀✨",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/59f22216-38df-463d-9dee-08cb16089b63/attendees
Content-Type: application/json

{
    "name": "Teste",
    "email": "teste@example.com"
}

###

GET http://localhost:3333/events/59f22216-38df-463d-9dee-08cb16089b63

###

GET http://localhost:3333/attendees/7/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/59f22216-38df-463d-9dee-08cb16089b63/attendees?pageIndex=0&query=Teste